// Shared mock data for tests

const mockGplayApps = [
  {
    appId: 'com.niche.tracker',
    title: 'Niche Tracker',
    developer: 'Indie Dev',
    score: 4.5,
    reviews: 50,
    minInstalls: 5000,
    free: true,
    price: 0,
    genre: 'Productivity',
    summary: 'A simple niche tracker app',
    description: 'A simple niche tracker app for daily use',
    url: 'https://play.google.com/store/apps/details?id=com.niche.tracker',
    updated: '2026-01-15',
  },
  {
    appId: 'com.popular.app',
    title: 'Popular App',
    developer: 'Big Corp',
    score: 4.8,
    reviews: 100000,
    minInstalls: 10000000,
    free: true,
    price: 0,
    genre: 'Productivity',
    summary: 'Very popular app',
    description: 'Very popular app used by millions',
    url: 'https://play.google.com/store/apps/details?id=com.popular.app',
    updated: '2026-03-01',
  },
  {
    appId: 'com.low.rated',
    title: 'Low Rated',
    developer: 'Bad Dev',
    score: 2.5,
    reviews: 30,
    minInstalls: 1000,
    free: true,
    price: 0,
    genre: 'Tools',
    summary: 'Low rated app',
    description: 'App with low rating',
    url: 'https://play.google.com/store/apps/details?id=com.low.rated',
    updated: '2026-02-01',
  },
  {
    appId: 'com.niche.gem',
    title: 'Hidden Gem',
    developer: 'Solo Dev',
    score: 4.7,
    reviews: 200,
    minInstalls: 10000,
    free: false,
    price: 2.99,
    genre: 'Health & Fitness',
    summary: 'A hidden gem fitness app',
    description: 'Track your fitness with this hidden gem',
    url: 'https://play.google.com/store/apps/details?id=com.niche.gem',
    updated: '2026-02-20',
  },
];

const mockAppStoreApps = [
  {
    id: 123456,
    appId: 'com.appstore.niche',
    title: 'AppStore Niche',
    developer: 'iOS Dev',
    score: 4.3,
    reviews: 80,
    free: true,
    price: 0,
    primaryGenre: 'Productivity',
    description: 'A niche App Store app',
    url: 'https://apps.apple.com/app/123456',
  },
  {
    id: 789012,
    appId: 'com.appstore.big',
    title: 'AppStore Big',
    developer: 'Apple Corp',
    score: 4.9,
    reviews: 500000,
    free: true,
    price: 0,
    primaryGenre: 'Social',
    description: 'Huge App Store app',
    url: 'https://apps.apple.com/app/789012',
  },
];

const mockGplayAppDetail = {
  appId: 'com.test.app',
  title: 'Test App',
  developer: 'Test Dev',
  score: 4.2,
  reviews: 1500,
  minInstalls: 50000,
  genre: 'Productivity',
  url: 'https://play.google.com/store/apps/details?id=com.test.app',
  histogram: { 1: 100, 2: 50, 3: 100, 4: 250, 5: 1000 },
};

const mockAppStoreDetail = {
  id: 123456,
  appId: 'com.test.iosapp',
  title: 'Test iOS App',
  developer: 'iOS Test Dev',
  score: 4.5,
  reviews: 800,
  primaryGenre: 'Productivity',
  url: 'https://apps.apple.com/app/123456',
};

const mockReviews = [
  { id: '1', score: 1, text: 'App crashes every time I open it. Terrible bug.' },
  { id: '2', score: 2, text: 'Too slow, loading takes forever. Lag is unbearable.' },
  { id: '3', score: 1, text: 'Too many ads everywhere. Popup ads are the worst.' },
  { id: '4', score: 5, text: 'Love this app! Clean design and beautiful interface.' },
  { id: '5', score: 4, text: 'Great app, wish it had dark mode. Please add offline support.' },
  { id: '6', score: 1, text: 'Crashes on startup, bug after the latest update.' },
  { id: '7', score: 2, text: "Can't export data, missing basic features. No way to backup." },
  { id: '8', score: 5, text: 'Best productivity app ever. Simple and effective.' },
  { id: '9', score: 3, text: 'It would be great if they add widgets. Needs improvement.' },
  { id: '10', score: 1, text: 'Privacy concerns - too many permissions required. Tracking data.' },
  { id: '11', score: 2, text: 'Pay to unlock basic features? Used to be free. Cash grab subscription.' },
  { id: '12', score: 4, text: 'Good app but should have notification reminders.' },
  { id: '13', score: 1, text: 'Error on every screen. Freeze when scrolling. Glitch everywhere.' },
  { id: '14', score: 5, text: 'Perfect! Does exactly what I need.' },
  { id: '15', score: 2, text: 'After update everything broke. New version is terrible.' },
];

module.exports = {
  mockGplayApps,
  mockAppStoreApps,
  mockGplayAppDetail,
  mockAppStoreDetail,
  mockReviews,
};
